ENV['RAILS_ENV'] ||= 'test'
require 'RMagick'
require 'kaleidoscope'
require 'pry'


include RSpec::Matchers

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec.configure do |config|
  config.before(:each) do
  end
  config.after(:each) do
  end
end